name: make

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cache binaries
      id: cache-bins
      uses: actions/cache@v2
      with:
        path: bin
        key: ${{ runner.os }}-bins
    - name: build
      run: make build
    - name: test
      run: make test
