name: make

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prepare env
      run: mkdir bin
    - name: build
      run: make build
    - name: test
      run: make test
